OSC/ondemand-packaging

web/ondemand/ondemand.spec
Added the OnDemand spec file used to build the RPM. Would it be possible to build an RPM from this to check that it works?
@treydock
=> Added OnDemand spec

web/ondemand-bc_osc_matlab/ondemand-bc_osc_matlab.spec, web/ondemand-bc_osc_matlab/v0.1.0.tar.gz, web/ondemand-bc_osc_matlab/v0.2.0.tar.gz
=> Bump bc_osc_matlab to 0.2.0

web/ondemand/ondemand.spec
This PR actually does a few things:
- sets web server (Apache & NGINX) configuration files as `%ghost`, so that the package does not maintain them other than removing them when uninstalling
- moves web server configuration changes & restarting to `%posttrans` so they don't pick up old configs during an upgrade
- fixes issues where `touch /path/to/app/tmp/restart.txt` would cause the RPM package to complain about these untracked files
- removes `bc_desktop` NGINX config file as it isn't a Passenger app
=> Set web server configs as ghost

README.md, passenger-release.ini, passenger-release.py
=> Add script to build and release passenger and nginx RPMs

release-manifest.yaml
@ericfranz @MorganRodgers This file changed represents the RPMs that will go into **1.4** release repos.
=> Update repo release manifest for 1.4 release

templates/app.spec, web/ondemand-bc_osc_abaqus/ondemand-bc_osc_abaqus.spec, web/ondemand-bc_osc_ansys_workbench/ondemand-bc_osc_ansys_workbench.spec, web/ondemand-bc_osc_comsol/ondemand-bc_osc_comsol.spec, web/ondemand-bc_osc_jupyter/ondemand-bc_osc_jupyter.spec, web/ondemand-bc_osc_jupyter_pitzer/ondemand-bc_osc_jupyter_pitzer.spec, web/ondemand-bc_osc_jupyter_spark/ondemand-bc_osc_jupyter_spark.spec, web/ondemand-bc_osc_matlab/ondemand-bc_osc_matlab.spec, web/ondemand-bc_osc_paraview/ondemand-bc_osc_paraview.spec, web/ondemand-bc_osc_rstudio_server/ondemand-bc_osc_rstudio_server.spec, web/ondemand-bc_osc_vmd/ondemand-bc_osc_vmd.spec, web/ondemand-pseudofun/ondemand-pseudofun.spec, web/ondemand-systemstatus/ondemand-systemstatus.spec
=> Add VERSION file for all apps

build/Rakefile, docker-image/env, docker-image/install.sh, docker-image/ondemand-el8-x86_64.cfg, packages/ondemand-runtime/ondemand-runtime.spec, rpm-sign.exp
Will fix ondemand builds for EL8
=> Numerous fixes after updating to Rocky 8 builds

packages/ondemand_exporter/ondemand_exporter.spec, release-manifest.yaml
=> Update ondemand_exporter packages to 0.8.1

packages/deb/ondemand-release-latest/debian/control, packages/deb/ondemand-release-latest/debian/postinst, packages/deb/ondemand-release-latest/debian/rules, packages/deb/ondemand-release/debian/control, packages/deb/ondemand-release/debian/postinst, packages/deb/ondemand-release/debian/rules
=> Use same Debian/Ubuntu release package name for all different OSes

lib/ood_packaging/build_box.rb
=> Improve invalid dist error handling

.gitlab-ci.yml
This is an attempt to force Gitlab pipelines to run before feature to build as gem is merged.
=> Copy gitlab-ci from feature/rake-task-gem

.github/workflows/e2e.yaml, .github/workflows/release.yaml
=> Add Github Actions to release buildbox and gem

.github/workflows/e2e.yaml, .gitlab-ci.yml, lib/ood_packaging/tasks.rb, lib/ood_packaging/version.rb, packages/python-websockify/rpm/python-websockify.spec
Fixes #163
Switch all Gitlab pipelines to use a matrix for dist
=> Add automation for compute packages

lib/ood_packaging/version.rb, packages/passenger/rpm/passenger.spec, release-manifest.yaml
=> Update Passenger to 6.0.14 and NGINX to 2.20.2

.github/workflows/e2e.yaml, .github/workflows/release.yaml, .github/workflows/unit.yaml, bin/ood_packaging, lib/ood_packaging/package.rb, lib/ood_packaging/utils.rb, lib/ood_packaging/version.rb, packages/ondemand-runtime/rpm/ondemand-runtime.spec
Bump Ruby used during Github Actions to 3.0.4
=> Bump EL builds to use Ruby 3.0

Gemfile.lock, lib/ood_packaging/build.rb, lib/ood_packaging/version.rb, packages/passenger/deb/debian/ondemand-nginx.changelog
Show packages after build
Bump version
=> Fix ondemand-nginx package version for Ubuntu builds

repo-update.sh, sync-release.py
Support Python 3 for sync-release.py
Allow repo-update.sh to run on RHEL8
=> Repo sync changes

repo-update.sh, sync-release.py
Support Python 3 and running on RHEL8
=> Repo sync changes (2.0)

lib/ood_packaging/build_box.rb
I just noticed these misspellings.
=> fix misspelled build

Gemfile.lock, lib/ood_packaging/version.rb, release-manifest.yaml
New release of ondemand-runtime, ondemand-release and ondemand-compute
=> First steps to prep 3.0 work

Gemfile.lock, lib/ood_packaging/build_box/docker-image/Dockerfile.erb, lib/ood_packaging/utils.rb, lib/ood_packaging/version.rb, packages/ondemand-release-latest/deb/debian/rules, packages/ondemand-release/deb/debian/rules, packages/ondemand-runtime/rpm/ondemand-runtime.spec, packages/passenger/rpm/passenger.spec, release-manifest.yaml, spec/ood_packaging/ood_packaging_spec.rb
Updates ondemand-runtime to 3.1.3
Updates ondemand-release packages for Ubuntu
=> Update to NodeJS 18 and Ruby 3.1 where possible

.github/workflows/e2e.yaml, .github/workflows/release.yaml, .gitlab-ci.yml, Gemfile.lock, lib/ood_packaging/build.rb, lib/ood_packaging/build_box.rb, lib/ood_packaging/build_box/docker-image/Dockerfile.erb, lib/ood_packaging/version.rb, packages/ondemand-release-latest/deb/debian/rules, packages/ondemand-release-latest/deb/debian/source/format, packages/ondemand-release/deb/debian/rules, packages/ondemand-release/deb/debian/source/format, release-manifest.yaml, release.py, repo-update.sh, spec/ood_packaging/build_spec.rb, sync-release.py
=> Support Debian 12 packages

Gemfile.lock, lib/ood_packaging/build_box/docker-image/Dockerfile.erb, lib/ood_packaging/version.rb, packages/ondemand-release-latest/deb/debian/rules, packages/ondemand-release/deb/debian/rules, release-manifest.yaml, spec/ood_packaging/ood_packaging_spec.rb
=> Update nodejs repo to use nodistro and new GPG key

lib/ood_packaging/version.rb, packages/python-websockify/rpm/python-websockify.spec, packages/turbovnc/rpm/turbovnc.spec, release-manifest.yaml
=> Upgrade to latest TurboVNC and python-websockify

lib/ood_packaging/build_box/docker-image/install.sh.erb
Fixes #295 though I'd still like someone to confirm it's not just an issue on my side.
=> chmod /etc/shadow to get passwordless sudo prompts
